language: python
cache: pip
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install flake8 pytest-cov pyDOE
  - pip install pytest --upgrade
  - pip install . --no-cache-dir
script:
  - pytest --cov=sbopt tests/
before_script:
  - flake8 sbopt
  - pytest --version
after_success:
  - pip install python-coveralls
  - pip install coverage==4.5.4
  - coveralls
